### ISSUE TITLE
NIST SP 800-90B no longer compiles

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#42]
```
...
element "mo" not allowed here; expected the element end-tag @ 5225:389
element "mn" not allowed here; expected the element end-tag @ 5225:399
element "mn" not allowed here; expected the element end-tag @ 5225:409
element "mn" not allowed here; expected the element end-tag @ 5225:421
element "math" not allowed here; expected the element end-tag or text @ 5229:78
element "mtext" not allowed here; expected the element end-tag @ 5229:101
element "math" not allowed here; expected the element end-tag or text @ 5232:78
element "math" not allowed here; expected the element end-tag or text @ 5235:78
element "mtext" not allowed here; expected the element end-tag @ 5235:101
element "math" not allowed here; expected the element end-tag or text @ 5238:78
element "math" not allowed here; expected the element end-tag or text @ 5241:78
element "mtext" not allowed here; expected the element end-tag @ 5241:101
element "math" not allowed here; expected the element end-tag or text @ 5244:78
element "math" not allowed here; expected the element end-tag or text @ 5247:78
element "mtext" not allowed here; expected the element end-tag @ 5247:101
element "math" not allowed here; expected the element end-tag or text @ 5250:78
IDREF "cbc-mac-spec" without matching ID @ 936:105
IDREF "cbc-mac-spec" without matching ID @ 5078:78
(... hang...)
```

The traceback on termination:

```sh
	40: from /Users/user/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
	39: from /Users/user/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
	38: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
	37: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	36: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
	35: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
	34: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	33: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
	32: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	31: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	30: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	29: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
	28: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
	27: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
	26: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
	25: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bin/metanorma:23:in `<top (required)>'
	24: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bin/metanorma:23:in `load'
	23: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/metanorma-cli-02b5ab4b96b1/exe/metanorma:230:in `<top (required)>'
	22: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/metanorma-e509d4d20fd7/lib/metanorma/compile.rb:18:in `compile'
	21: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/metanorma-e509d4d20fd7/lib/metanorma/compile.rb:119:in `process_extensions'
	20: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/metanorma-e509d4d20fd7/lib/metanorma/compile.rb:119:in `each'
	19: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/metanorma-e509d4d20fd7/lib/metanorma/compile.rb:128:in `block in process_extensions'
	18: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/metanorma-nist-988d1fdf1880/lib/metanorma/nist/processor.rb:34:in `output'
	17: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/isodoc-645360ee73db/lib/isodoc/convert.rb:151:in `convert'
	16: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/isodoc-645360ee73db/lib/isodoc/word_function/postprocess.rb:37:in `postprocess'
	15: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/isodoc-645360ee73db/lib/isodoc/word_function/postprocess.rb:44:in `toWord'
	14: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/html2doc-396aad74ed9b/lib/html2doc/base.rb:12:in `process'
	13: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/html2doc-396aad74ed9b/lib/html2doc/base.rb:36:in `process_html'
	12: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/html2doc-396aad74ed9b/lib/html2doc/base.rb:49:in `cleanup'
	11: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/html2doc-396aad74ed9b/lib/html2doc/math.rb:39:in `mathml_to_ooml'
	10: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri/xml/node_set.rb:203:in `each'
	 9: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri/xml/node_set.rb:203:in `upto'
	 8: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri/xml/node_set.rb:204:in `block in each'
	 7: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/html2doc-396aad74ed9b/lib/html2doc/math.rb:40:in `block in mathml_to_ooml'
	 6: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/html2doc-396aad74ed9b/lib/html2doc/math.rb:30:in `ooxml_cleanup'
	 5: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri/xml/document.rb:168:in `collect_namespaces'
	 4: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri/xml/document.rb:168:in `inject'
	 3: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri/xml/node_set.rb:203:in `each'
	 2: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri/xml/node_set.rb:203:in `upto'
	 1: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri/xml/node_set.rb:204:in `block in each'
/Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri/xml/document.rb:171:in `block in collect_namespaces': Interrupt

```

**Comment by opoudjis** [comment]
It compiles, I believe; it's just taking monstrously long to do the MathML to OOXML conversions. These are done through XSLT of a sizeable stylesheet (should be 17 mins for document); I will look into either parallelising execution, or finding  a better gem to invoke from html2doc.

**Comment by opoudjis** [comment]
Have been using https://github.com/glejeune/ruby-xslt; will try out Nokogiri XSLT.

**Comment by opoudjis** [comment]
I will use Nokogiri XSLT for compactness, but it is no faster. Rather than look for a fast XSLT library which may cut corners, I will parallellise it.

**Comment by opoudjis** [comment]
Turns out this was a different issue: each execution of XSLT transformation on a MathML expression was collecting the namespaces of the Nokogiri document, which is extremely time consuming. Have factored that fetching out of the loop: conversion now runs fast enough that parallelisation is no longer required.

**Comment by opoudjis** [comment]
Fixed in html2doc

**Comment by ronaldtse** [comment]
Thank you @opoudjis !!
